from .utils import get_max_min_attribute

position_weights = {
    'GK': {
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 1,
        'Min': 0,
        'Goal': 0,
        'Asis': 1,
        'xG': 0,
        'Gol_90': 0,
        'Asis_90': 1,
        'Goal_allowed': -5,
        'Clean_sheet': 5,
        'Sv_rat': 4,
        'xSv_rat': 4,
        'Pen_saved_rat': 5,
        'Faga': 1,
        'Fcomm': -3,
        'Yel': -3,
        'Red': -5,
        'Dist_90': 0,
        'Key_tck_90': 4,
        'Key_hdr_90': 4,
        'Blocks_90': 3,
        'Clr_90': 4,
        'Int_90': 4,
        'Hdr_rat': 4,
        'Tackles_rat': 4,
        'Gl_mistake': -7,
        'Pass_rat': 5,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 0,
        'Conv_rat': 0
    },
    'DC': {
        # Define attributes for DC position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
        

    },
    'DL': {
        # Define attributes for DL position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'DR': {
        # Define attributes for DR position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'DM': {
        # Define attributes for DM position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'WBL': {
        # Define attributes for WBL position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'WBR': {
        # Define attributes for WBR position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'MC': {
        # Define attributes for MC position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'ML': {
        # Define attributes for ML position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'MR': {
        # Define attributes for MR position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'AMC': {
        # Define attributes for AMC position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'AML': {
        # Define attributes for AML position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'AMR': {
        # Define attributes for AMR position
        'International_match': 0,
        'CAbil': 4,
        'Pot_abil': 6,
        'Strater_match': 5,
        'Res_match': 2,
        'Min': 3,
        'Goal': 5,
        'Asis': 3,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 3,
        'Goal_allowed': -6,
        'Clean_sheet': 6,
        'Sv_rat': 0,
        'xSv_rat': 0,
        'Pen_saved_rat': 0,
        'Faga': 1,
        'Fcomm': -4,
        'Yel': -3,
        'Red': -7,
        'Dist_90': 3,
        'Key_tck_90': 6,
        'Key_hdr_90': 6,
        'Blocks_90': 5,
        'Clr_90': 6,
        'Int_90': 6,
        'Hdr_rat': 6,
        'Tackles_rat': 6,
        'Gl_mistake': -8,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 4,
        'Cr_c_90': 3,
        'Cr_c_acc': 3,
        'Ch_c_90': 3,
        'Drb_90': 1,
        'Poss_lost_90': -2,
        'Shot_rat': 1,
        'Conv_rat': 1
    },
    'STC': {
        'International_match': 1,
        'CAbil': 5,
        'Pot_abil': 5,
        'Strater_match': 4,
        'Res_match': 3,
        'Min': 4,
        'Goal': 5,
        'Asis': 4,
        'xG': 5,
        'Gol_90': 5,
        'Asis_90': 4,
        'Goal_allowed': -2,
        'Clean_sheet': -3,
        'Sv_rat': -2,
        'xSv_rat': -2,
        'Pen_saved_rat': -2,
        'Faga': -3,
        'Fcomm': -3,
        'Yel': -2,
        'Red': -5,
        'Dist_90': 3,
        'Key_tck_90': 2,
        'Key_hdr_90': 2,
        'Blocks_90': 2,
        'Clr_90': 2,
        'Int_90': 2,
        'Hdr_rat': 2,
        'Tackles_rat': 2,
        'Gl_mistake': -4,
        'Pass_rat': 4,
        'Pr_pass_90': 4,
        'Key_pass_90': 5,
        'Cr_c_90': 5,
        'Cr_c_acc': 4,
        'Ch_c_90': 5,
        'Drb_90': 5,
        'Poss_lost_90': -3,
        'Shot_rat': 5,
        'Conv_rat': 5
    }
}


def smart_score(player, pos, weights, budget, short_term, long_term):
    smart_score = 0

    for attribute, weight in weights.items():
        max, min = get_max_min_attribute(attribute, player.get(pos))
        # Normalize attribute value if necessary
        normalized_value = normalize(player.get(attribute), min, max)
        smart_score += normalized_value * weight

       # Adjust score based on potential ability
    if player.get('Pot_abil') > player.get('CAbil'):
        smart_score *= 1.2  # Increase score if potential ability is higher than current ability
    else:
        smart_score *= 0.9  # Decrease score if potential ability is lower than or equal to current ability

    # Adjust score based on age
    if 16 <= player.get('age') <= 25:
        smart_score *= 1.2  # Increase score for players aged 16-25
    else:
        smart_score *= 0.9  # Decrease score for players outside the age range

     # Adjust score based on international match experience
    int_matches = player.get('Int_match', 0)
    if int_matches > 300:
        smart_score *= 0.8  # Decrease score for players with more than 10 international matches
    elif 150 < int_matches <= 300:
        smart_score *= 0.9  # Decrease score for players with 6-10 international matches
    elif 50 < int_matches <= 150:
        smart_score *= 0.95  # Decrease score for players with 2-5 international matches


    
    #smart_score *= adjust_for_budget(budget) * adjust_for_expectations(short_term, long_term)

    #tener en cuenta market_value, LIga, equipo?, Contrato?, salario?, partidos int (negativo para equipo + desgaste?) edad, altura peso? (depende posicion?), (pie))?
    return smart_score

def normalize(value, min, max):
    # Normalize value to a range between 0 and 1

    normalized_value = (value - min) / (max - min)

    return normalized_value

def adjust_for_budget(budget):
    # Adjust score based on budget constraints
    # Implement adjustment logic here
    pass

def adjust_for_expectations(short_term, long_term):
    # Adjust score based on short-term and long-term expectations
    # Implement adjustment logic here
    pass


