# Generated by Django 5.0.1 on 2024-02-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('custom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Nacionality', models.CharField(max_length=5)),
                ('International_match', models.IntegerField()),
                ('Club', models.CharField(max_length=100)),
                ('League', models.CharField(max_length=100)),
                ('Pref_foot', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('End_contract', models.DateField()),
                ('CAbil', models.IntegerField()),
                ('Pot_abil', models.IntegerField()),
                ('Strater_match', models.IntegerField()),
                ('Res_match', models.IntegerField()),
                ('Min', models.IntegerField()),
                ('Goal', models.IntegerField()),
                ('Asis', models.IntegerField()),
                ('xG', models.FloatField()),
                ('Gol_90', models.FloatField()),
                ('Asis_90', models.FloatField()),
                ('Goal_allowed', models.IntegerField()),
                ('Clean_sheet', models.IntegerField()),
                ('Sv_rat', models.IntegerField()),
                ('xSv_rat', models.IntegerField()),
                ('Pen_saved_rat', models.IntegerField()),
                ('Faga', models.IntegerField()),
                ('Fcomm', models.IntegerField()),
                ('Yel', models.IntegerField()),
                ('Red', models.IntegerField()),
                ('Dist_90', models.FloatField()),
                ('Key_tck_90', models.FloatField()),
                ('Key_hdr_90', models.FloatField()),
                ('Blocks_90', models.FloatField()),
                ('Clr_90', models.FloatField()),
                ('Int_90', models.FloatField()),
                ('Hdr_rat', models.IntegerField()),
                ('Tackles_rat', models.IntegerField()),
                ('Gl_mistake', models.IntegerField()),
                ('Pass_rat', models.IntegerField()),
                ('Pr_pass_90', models.IntegerField()),
                ('Key_pass_90', models.IntegerField()),
                ('Cr_c_90', models.FloatField()),
                ('Cr_c_acc', models.IntegerField()),
                ('Ch_c_90', models.FloatField()),
                ('Drb_90', models.FloatField()),
                ('Poss_lost_90', models.FloatField()),
                ('Shot_rat', models.IntegerField()),
                ('Conv_rat', models.IntegerField()),
                ('Dorsal', models.IntegerField()),
                ('Country_league', models.CharField(max_length=100)),
                ('Pos', models.ManyToManyField(to='smartscore.position')),
            ],
        ),
    ]
