# Generated by Django 5.0.1 on 2024-02-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('custom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Nacionalidad', models.CharField(max_length=5)),
                ('Internacionalidades', models.IntegerField()),
                ('Pos', models.CharField(max_length=50)),
                ('Altura', models.IntegerField()),
                ('Peso', models.IntegerField()),
                ('Sueldo', models.IntegerField()),
                ('Final', models.DateField()),
                ('Part', models.IntegerField()),
                ('Enc', models.IntegerField()),
                ('Clean_sheet', models.IntegerField()),
                ('Pen_metidos_rat', models.IntegerField()),
                ('Dist_90', models.IntegerField()),
                ('Pep', models.IntegerField()),
                ('On_target_rat', models.IntegerField()),
            ],
        ),
    ]
