# Generated by Django 5.0.1 on 2024-02-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='Pos',
        ),
        migrations.AddField(
            model_name='player',
            name='Pos',
            field=models.ManyToManyField(to='smartscore.position'),
        ),
    ]
