# Generated by Django 5.0.1 on 2024-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Key_pass_90',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='Pr_pass_90',
            field=models.FloatField(),
        ),
    ]
