# Generated by Django 5.0.1 on 2024-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscore', '0003_userprofile_budget_userprofile_expectations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='futureScope',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='budget',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='league',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
