# Generated by Django 5.0.1 on 2024-03-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscore', '0004_remove_userprofile_futurescope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='End_contract',
            field=models.DateField(null=True),
        ),
    ]
